import React from 'react'

const Main = () => {
    return (
        <div className='mx-20 my-10'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque nec nam aliquam sem. Pharetra et ultrices neque ornare aenean euismod. Vulputate dignissim suspendisse in est. At risus viverra adipiscing at in. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Arcu dui vivamus arcu felis bibendum ut tristique. Sed nisi lacus sed viverra tellus in. Quis viverra nibh cras pulvinar mattis. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Nunc congue nisi vitae suscipit tellus mauris a diam. Lectus nulla at volutpat diam ut. Sapien et ligula ullamcorper malesuada proin libero nunc consequat interdum. Dictum sit amet justo donec enim diam vulputate. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Nunc eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Facilisi etiam dignissim diam quis. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Elit ut aliquam purus sit amet luctus venenatis. Orci sagittis eu volutpat odio facilisis mauris sit amet massa.

            Ullamcorper a lacus vestibulum sed arcu non odio euismod. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Donec ac odio tempor orci dapibus ultrices in. Mauris pharetra et ultrices neque ornare. Id volutpat lacus laoreet non curabitur gravida arcu ac. Pharetra et ultrices neque ornare aenean euismod elementum. Urna porttitor rhoncus dolor purus non. Sit amet dictum sit amet justo donec enim diam. Vitae congue eu consequat ac felis donec. Sem et tortor consequat id porta nibh venenatis.

            Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Nullam ac tortor vitae purus faucibus ornare suspendisse sed. Dapibus ultrices in iaculis nunc sed augue lacus viverra vitae. Sem fringilla ut morbi tincidunt augue interdum velit. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Semper quis lectus nulla at volutpat diam ut venenatis tellus. Massa ultricies mi quis hendrerit. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Nulla pellentesque dignissim enim sit amet venenatis urna cursus. Risus viverra adipiscing at in tellus. Nisi porta lorem mollis aliquam ut porttitor leo. Nunc sed id semper risus in hendrerit gravida rutrum. Eget arcu dictum varius duis at consectetur lorem donec massa. Ut tristique et egestas quis. Velit laoreet id donec ultrices tincidunt arcu non sodales. Maecenas sed enim ut sem viverra aliquet eget sit. Egestas sed sed risus pretium quam. Vulputate dignissim suspendisse in est ante in. Eros in cursus turpis massa tincidunt.

            Enim ut tellus elementum sagittis vitae et leo. Diam phasellus vestibulum lorem sed risus ultricies tristique. Orci ac auctor augue mauris augue neque gravida in fermentum. Tincidunt ornare massa eget egestas purus viverra. Id porta nibh venenatis cras sed felis eget velit. Eget magna fermentum iaculis eu non. Sit amet justo donec enim. Mi quis hendrerit dolor magna. Ligula ullamcorper malesuada proin libero. Vel eros donec ac odio tempor orci dapibus ultrices in. Dignissim diam quis enim lobortis. Dictum sit amet justo donec. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Tellus orci ac auctor augue. Quisque non tellus orci ac auctor augue mauris augue.

            Consectetur a erat nam at lectus urna duis. Lacus viverra vitae congue eu consequat ac felis donec et. Id interdum velit laoreet id donec. Molestie at elementum eu facilisis sed odio morbi quis commodo. Lorem ipsum dolor sit amet consectetur adipiscing. Faucibus purus in massa tempor nec feugiat nisl. Fringilla ut morbi tincidunt augue interdum velit euismod in. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Cursus euismod quis viverra nibh cras pulvinar mattis nunc. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Sed odio morbi quis commodo odio aenean. Ullamcorper a lacus vestibulum sed arcu non odio. Aliquet nec ullamcorper sit amet risus nullam eget felis eget.

            Arcu cursus vitae congue mauris. Enim ut sem viverra aliquet. Est ullamcorper eget nulla facilisi. Porttitor rhoncus dolor purus non. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Ut aliquam purus sit amet. Turpis egestas integer eget aliquet nibh praesent. Sagittis aliquam malesuada bibendum arcu. Blandit libero volutpat sed cras ornare arcu dui vivamus. Purus semper eget duis at tellus.

            Mauris pharetra et ultrices neque ornare aenean euismod elementum. Commodo elit at imperdiet dui accumsan. Velit laoreet id donec ultrices tincidunt arcu non sodales. Nec ullamcorper sit amet risus nullam eget felis eget. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Nunc sed velit dignissim sodales. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Ac feugiat sed lectus vestibulum. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Pharetra magna ac placerat vestibulum. Massa ultricies mi quis hendrerit dolor magna eget est. Arcu dictum varius duis at consectetur lorem. Egestas dui id ornare arcu odio ut sem. Volutpat diam ut venenatis tellus in metus vulputate. Sed turpis tincidunt id aliquet. Pulvinar etiam non quam lacus. Netus et malesuada fames ac turpis egestas maecenas.

            Ac feugiat sed lectus vestibulum mattis. Ultrices vitae auctor eu augue ut. Turpis in eu mi bibendum neque egestas congue quisque egestas. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Morbi tristique senectus et netus et malesuada fames ac. Facilisis mauris sit amet massa vitae tortor condimentum lacinia. Id aliquet lectus proin nibh nisl condimentum. Morbi quis commodo odio aenean sed adipiscing diam. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. In fermentum et sollicitudin ac orci. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Cursus sit amet dictum sit amet justo donec enim diam.

            Interdum varius sit amet mattis vulputate enim. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Turpis cursus in hac habitasse. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Maecenas volutpat blandit aliquam etiam erat velit. Tellus at urna condimentum mattis. Risus feugiat in ante metus dictum. Volutpat sed cras ornare arcu dui vivamus. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Blandit massa enim nec dui nunc mattis enim ut. Enim nec dui nunc mattis enim. Arcu risus quis varius quam quisque id diam vel. Hac habitasse platea dictumst quisque sagittis. Commodo nulla facilisi nullam vehicula ipsum a. Nisl rhoncus mattis rhoncus urna neque. Id eu nisl nunc mi. At augue eget arcu dictum varius duis at. In nibh mauris cursus mattis molestie.

            Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Molestie nunc non blandit massa enim nec dui nunc. Vitae justo eget magna fermentum. Sit amet aliquam id diam maecenas ultricies mi eget. Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Nullam vehicula ipsum a arcu cursus vitae congue. Malesuada pellentesque elit eget gravida cum. Augue lacus viverra vitae congue eu consequat ac. Velit sed ullamcorper morbi tincidunt. Integer malesuada nunc vel risus commodo viverra. Velit egestas dui id ornare arcu odio ut sem. Consectetur libero id faucibus nisl tincidunt eget nullam. Mauris cursus mattis molestie a iaculis at erat pellentesque.
            Ac feugiat sed lectus vestibulum mattis. Ultrices vitae auctor eu augue ut. Turpis in eu mi bibendum neque egestas congue quisque egestas. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Morbi tristique senectus et netus et malesuada fames ac. Facilisis mauris sit amet massa vitae tortor condimentum lacinia. Id aliquet lectus proin nibh nisl condimentum. Morbi quis commodo odio aenean sed adipiscing diam. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. In fermentum et sollicitudin ac orci. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Cursus sit amet dictum sit amet justo donec enim diam.

            Interdum varius sit amet mattis vulputate enim. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Turpis cursus in hac habitasse. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Maecenas volutpat blandit aliquam etiam erat velit. Tellus at urna condimentum mattis. Risus feugiat in ante metus dictum. Volutpat sed cras ornare arcu dui vivamus. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Blandit massa enim nec dui nunc mattis enim ut. Enim nec dui nunc mattis enim. Arcu risus quis varius quam quisque id diam vel. Hac habitasse platea dictumst quisque sagittis. Commodo nulla facilisi nullam vehicula ipsum a. Nisl rhoncus mattis rhoncus urna neque. Id eu nisl nunc mi. At augue eget arcu dictum varius duis at. In nibh mauris cursus mattis molestie.Ac feugiat sed lectus vestibulum mattis. Ultrices vitae auctor eu augue ut. Turpis in eu mi bibendum neque egestas congue quisque egestas. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Morbi tristique senectus et netus et malesuada fames ac. Facilisis mauris sit amet massa vitae tortor condimentum lacinia. Id aliquet lectus proin nibh nisl condimentum. Morbi quis commodo odio aenean sed adipiscing diam. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. In fermentum et sollicitudin ac orci. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Cursus sit amet dictum sit amet justo donec enim diam.

            Interdum varius sit amet mattis vulputate enim. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Turpis cursus in hac habitasse. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Maecenas volutpat blandit aliquam etiam erat velit. Tellus at urna condimentum mattis. Risus feugiat in ante metus dictum. Volutpat sed cras ornare arcu dui vivamus. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Blandit massa enim nec dui nunc mattis enim ut. Enim nec dui nunc mattis enim. Arcu risus quis varius quam quisque id diam vel. Hac habitasse platea dictumst quisque sagittis. Commodo nulla facilisi nullam vehicula ipsum a. Nisl rhoncus mattis rhoncus urna neque. Id eu nisl nunc mi. At augue eget arcu dictum varius duis at. In nibh mauris cursus mattis molestie.
        </div>
    )
}

export default Main